SELECT
    fr.id,
    fr.event_id,
  	fr.url,
	fr.title,
	fr.lead_text,
	fr.description,
	fr.date_start::DATE AS date_start,
	fr.date_end::DATE AS date_end,
	fr.is_outdated,
    a.tous_les_creneaux,
	a.nb_total_occurences,
	a.prochains_creneaux,
	a.nb_next_occurrences,
	a.next_start_date,
	a.has_event_today,
	fr.date_description,
	fr.cover_url,
	fr.cover_credit,
	fr.address_name,
	fr.address_street,
	fr.address_zipcode,
	fr.lat,
	fr.lon,
	fr.address_is_indicated,
	fr.pmr,
	fr.blind,
	fr.deaf,
	fr.sign_language,
	fr.mental,
	fr.contact_url,
	fr.contact_phone,
	fr.contact_mail,
	fr.contact_facebook,
	fr.price_type,
	fr.price_detail,
	fr.access_link,
	fr.access_link_text,
	fr.updated_at,
	fr.programs,
	fr.title_event,
	fr.audience,
	fr.rank,
	fr.qfap_tags,
	fr.contact_organisation_name,
	fr.contact_url_text,
	fr.contact_instagram
FROM {{ ref('filtered_rows') }} fr
LEFT JOIN {{ ref('agenda') }} a
ON fr.id = a.id
