select
	id,
	event_id,
  	"url",
	title,
	lead_text,
	"description",
	date_start,
	date_end,
	CASE WHEN date_end < current_localtimestamp() THEN TRUE ELSE FALSE END AS is_outdated,
	occurrences,
	date_description,
	cover_url,
	cover_credit,
	address_name,
	address_street,
	address_zipcode,
	ST_X(lat_lon) as lon,
	ST_Y(lat_lon) as lat,
	CASE WHEN (address_name IS NULL AND address_street IS NULL AND address_zipcode IS NULL) THEN FALSE ELSE TRUE END AS address_is_indicated,
	pmr,
	blind,
	deaf,
	sign_language,
	mental,
	contact_url,
	contact_phone,
	contact_mail,
	contact_facebook,
	price_type,
	CASE price_detail
		WHEN '<p></p>' THEN NULL
		WHEN '<p></p><p></p>' THEN NULL
		ELSE price_detail END AS price_detail,
	access_link,
	access_link_text,
	updated_at,
	programs,
	title_event,
	audience,
	rank,
	qfap_tags,
	contact_organisation_name,
	contact_url_text,
	contact_instagram
from {{ ref('raw_events') }}
