SELECT
    id,
    event_id,
  	"url",
	title,
	lead_text,
	title_event,
	"description",
	audience,
	price_type,
	price_detail,
	date_start,
	date_end,
    tous_les_creneaux,
	nb_total_occurences,
	prochains_creneaux,
	nb_next_occurrences,
	next_start_date,
	has_event_today,
	date_description,
	programs,
	lower(qfap_tags) AS qfap_tags,
	rank,
	cover_url,
	cover_credit,
	address_name,
	address_zipcode,
	CASE WHEN address_is_indicated THEN concat(address_street, ' ', address_zipcode) ELSE NULL END AS full_address,
	CASE WHEN full_address IS NOT NULL THEN lat ELSE NULL END AS latitude,
	CASE WHEN full_address IS NOT NULL THEN lon ELSE NULL END AS longitude,
	CASE WHEN pmr is NULL THEN 0 ELSE pmr::INT END as pmr_friendly,
	CASE WHEN blind is NULL THEN 0 ELSE blind::INT END as blind_friendly,
	CASE WHEN deaf is NULL THEN 0 ELSE deaf::INT END as deaf_friendly,
	CASE WHEN sign_language is NULL THEN 0 ELSE sign_language::INT END as sign_language_friendly,
	CASE WHEN mental is NULL THEN 0 ELSE mental::INT END as mental_friendly,
	struct_pack(pmr := pmr_friendly, blind := blind_friendly, deaf := deaf_friendly, sign_language := sign_language_friendly, mental := mental_friendly) as handicap_friendly_details,
	CASE WHEN (pmr_friendly = 1 or blind_friendly = 1 or deaf_friendly = 1 or sign_language_friendly = 1 or mental_friendly = 1)  THEN TRUE ELSE FALSE END as is_handicap_friendly,
	contact_url,
	contact_phone,
	contact_mail,
	contact_facebook,
	access_link AS ticket_resa_and_more_url,
	contact_organisation_name,
	contact_url_text,
	contact_instagram,
	updated_at,
FROM {{ ref('agenda_enriched') }}
WHERE is_outdated IS FALSE
ORDER BY rank DESC
